lib/whimsy/asf/agenda/attachments.rb

Not currently used by functions other than Whimsy agenda email capability.
Helps chairs with their filtering, and avoids putting direct forwarding
address into the copied list archives.

use @apache.org address for chairs

---

www/members/proxy.cgi

Instead of building the list from files, then attempting to add back text,
retain the original text but add any files that were not found based on the
user ID

retain other markers in proxy form

---

www/classic/roster/js/app._js
www/roster/views/committee.js.rb
www/roster/views/pmc/pmc.js.rb

The actual file handling committee info in svn is:
https://svn.apache.org/repos/private/committers/board/committee-info.txt

Fix typo in references to committee-info.txt

---

www/board/agenda/models/minutes.rb
www/board/agenda/views/pages/report.js.rb

Two forms will be supported:
1) entirely contained on one line, optionally with text before and after.
2) where <private> is the first non-blank on a line, and </private> is the
last non-blank on a line.  Note: text may follow the open tag and precede
the close tag.
It turns out the hardest part of this is determining what white space
needs to be removed in conjunction with the private markers.
clr: I'd like to see a bit more commentary (especially with regular expressions).
For example,
// remove entire lines starting with <private>... and ending with ...</private>
// remove private comments from inside a line containing ...<private>...</private>...

add support for inline private sections (commented)

---

lib/whimsy/asf/themes.rb
www/committers/tools.cgi
www/test/test.cgi

Comments/suggestions for how to better show a consistent layout for users, including both a "what is this script" block as well as a short listing of related tools?

Show proposed new way to provide related links/helpblock in any script

---

lib/whimsy/asf/podlings.rb
www/roster/models/ppmc.rb
www/roster/views/ppmc/main.js.rb

- Separate out the monthly and normal reporting schedules
- Change text for podling reports to indicate Board Reports
- Don't reorder reporting schedule

Minor changes to the podling pages:

---

lib/whimsy/asf/agenda.rb
lib/whimsy/asf/agenda/exec-officer.rb
lib/whimsy/asf/agenda/minutes.rb
lib/whimsy/asf/agenda/special.rb
lib/whimsy/asf/agenda/summary.rb

Produces results for pre-2007 agendas, and doesn’t affect parsing of later ones. @rubys  Needs review to ensure there isn't something else that this will erroneously report incorrect data (where it used to report correct data).

Allow fallback parsing of pre-2007 agendas

---

www/secretary/workbench/img2pdf
www/secretary/workbench/models/attachment.rb
www/secretary/workbench/views/actions/rotate-attachment.json.rb

To be applied after https://github.com/apache/infrastructure-puppet/pull/1227 lands

switch to the pip3 version of img2pdf

---

lib/whimsy/asf/committee.rb

per Sam's comment on this INFRA Jira ticket:
https://issues.apache.org/jira/browse/INFRA-18453?focusedCommentId=16845838&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16845838
this PR does the following:
- trims trailing spaces in the `committee.rb` file. my editor does this automatically, so I figure it's worthwhile committing
- adds the `diversity` mapping for the Diversity and Inclusion committee
- fixes a formatting issue with the hash items
- sorts the hash lines by key
I seperated out the cosmetic changes in case that's the way it should be done for this project. I can squash them if you want. or I can remove them from the PR

add mapping for Diversity and Inclusion committee

---

www/secretary/workbench/views/actions/check-signature.json.rb

This changes the default keyserver to keys.openpgp.org which has protections against recently exploited weaknesses in the current SKS pool.

[WHIMSY-274] Use keys.openpgp.org

---

www/board/agenda/templates/agenda.erb

This updates the teleconference info to use zoom now hosted by the ASF Secretary.
CC @wohali

Migrate teleconference to zoom

---

www/members/inactive.cgi

The following page https://whimsy.apache.org/members/inactive.cgi returns an error when now statistics are available (e.g. for newly elected members).
This PR solves the nil error and returns the following in case no statistics are available:
Hope the fix is in the correct place ;)

Fix for newly elected members statistics

---

www/members/watch.cgi

nominated-members.txt changed format between 2019 and 2020 (I don't know why) to list userid first, and then full name. This matches the new format. 
Note that this will also match previous year's file format, but INCORRECTLY. ie, will assume that person's first name is their availid.
So, in summary, changing the file format was probably a bad move, and maybe reverting THAT is actually the correct fix here.

The file format changed in 2020, and this matches the new format

---

www/members/nominations.cgi

Fixes regex to match the new format of the nominated-members.txt file. Specifically, since we now have "availaid FNAME LNAME:" we need to discard the availid to match the email subject line, and (maybe?) the ":" from the end of the line.
Again ... why did we change the file format?

Fixes regex to match the new format of the nominated-members.txt file

---

lib/whimsy/sitestandards.rb
repository.yml
tools/site-scan.rb
www/roster/models/committee.rb
www/roster/models/nonpmc.rb
www/roster/views/nonpmc/main.js.rb
www/roster/views/pmc/main.js.rb

As requested per [WHIMSY-314](https://issues.apache.org/jira/browse/WHIMSY-314) apache.org/img/ has been replaced with apache.org/logos/

WHIMSY-314: Replaced a.o/img/ with a.o/logos/

---

lib/whimsy/asf/documents.rb
repository.yml
www/roster/models/committer.rb
www/roster/views/person/forms.js.rb

The roster entry for a member currently includes links to two files: the ICLA as originally filed, and the Member Application. Since they are links, they might be directories or pdf files.
This pull request (not tested) attempts to add any files either in the emeritus directory or the emeritus-requests-received directory that matches the member's name.

add emeritus files and emeritus-request files to member info

---

www/board/agenda/models/minutes.rb
www/board/agenda/spec/secretary_spec.rb
www/board/agenda/test/data/board_minutes_2015_01_21.txt

This should change the minuted agenda time so that it is marked as UTC instead of Pacific. Note that the secretary is already recording the time as UTC, so we don't need to change the time digits.
I have not tested it, since I don't have a test setup, but my imagination says it will work just fine. YMMV.

change agenda minuted adjournment time to UTC

---

www/board/agenda/README.md

The pre-reqs need to include the development packages to build native extensions during the `bundle install` phase.

Updated prereqs

---

README.md

This change repairs the Travis CI build status. The badge currently appears as a broken image and the build status is not obtainable.
This change also corrects a couple minor typos.

Repair Travis build status

---

DEVELOPMENT.md

Standardize backticks in Markdown [skip ci]

---

www/board/agenda/views/buttons/add-comment.js.rb

Updating the displayed field description to match reality; we switched away from initials to using Apache IDs a while back.

Update add comment label display

---

lib/whimsy/sitestandards.rb

Update guidance on site-check to reference Community Over Code, and the main events.apache.org website.

Update guidance on site-check to reference Community Over Code, and the
