apache/whimsy

www/board/agenda/views/layout/footer.js.rb

Nav arrows show corresponding status color

---

LICENSE

Now I'm wondering if this is an actual mistake, or trolling to see if people were paying attention :smiling_imp:

Add the license

---

config/whimsy.conf
www/secmail/views/forms/incomplete.js.rb
www/secmail/views/forms/unsigned.js.rb
www/secretary/workbench/file.cgi
www/secretary/workbench/publickey.erb
www/secretary/workbench/worklist.cgi
www/secretary/workbench/worklist.js

Please review this change and merge if it looks ok.

Incomplete unsigned

---

www/secmail/views/forms/icla.js.rb

default both real name and public name to email name
default file name to real name not public name

Change icla form:

---

www/test/apachecon.cgi

@ShaneCurcuru perhaps the pages should redirect?

make the page redirect to the new location

---

www/roster/main.rb
www/roster/models/orgchart.rb
www/roster/views/duties.html.rb

In preparation for creating a public version.  If someone else could eyeball if there is anything I missed (or if there's a better way to read this data), that'd be appreciated.

Add descriptions to orgchart/duties table

---

lib/whimsy/asf/themes.rb
www/test/dataflow.cgi
www/test/test.cgi

The new _whimsy_body/_whimsy_body2 are proposals for a better way to use bootstrap styles and provide even simpler themes with minimal code for script writers.

Preliminary work for providing simpler bootstrap styles

---

www/401.html
www/404.html
www/500.html
www/incubator/podlings/by-age.cgi

I'd like to keep the whimsy style consistent, so how about this for a new style for any incubator related tools?  It keeps the incubator egg logo, but otherwise uses the common bootstrap styles used on other whimsy pages.
Review requested by @johnament

Proposed new whimsy style for incubator pages

---

lib/whimsy/asf/podlings.rb

This should fix the unexpected format change.

Re-add the hash of podlings, it wasn't the change I was looking for.

---

www/members/memberless-pmcs.cgi

The buttons seem to show *less than* the number displayed.

Fixed typo

---

www/roster/views/ppmc/establish.text.rb

Removes Bylaws clause from Podling Graduation Resolution text

WHIMSY-252

---

MACOSX.md

1. Brew installation and patches for openldap and apr-util formulae
2. rbenv Ruby installation
3. Full gem install list
4. Update to include mod_negotiation

Updated MacOS Instructions

---

.gitignore
www/secretary/workbench/templates/icla-account-requested.erb
www/secretary/workbench/templates/icla-invalid-id.erb
www/secretary/workbench/templates/icla-pmc-notified.erb
www/secretary/workbench/templates/icla.erb
www/secretary/workbench/templates/incomplete.erb
www/secretary/workbench/templates/pubkey.erb
www/secretary/workbench/templates/unsigned.erb

Various little things, mostly inside the email templates.

Code cleanups

---

DOCKER.md
Rakefile
docker/docker-compose.yaml
lib/whimsy/asf/config.rb

This may provide access to CA certificates?

have docker mount users home directory

---

www/board/agenda/views/actions/remind-actions.json.rb

remove board cc, add b-p bcc for AI reminders

remove board cc, add b-p bcc

---

www/members/proxy.cgi

pulled from Meetings/*/proxies on Feb 4.

add the current proxy volunteers

---

www/board/agenda/templates/agenda.erb

Allow comments on Chair, Treasurer, Secretary, EVP, and Vice Chair

Update board agenda to allow comments on Officers

---

www/secretary/workbench/server.rb
www/secretary/workbench/views/forms/emeritus-request.js.rb

A few small updates, now stuck with an error when submitting the form.

Emeritus request updates

---

www/secretary/workbench/config.rb
www/secretary/workbench/views/parts.html.rb

* Homebrew location for gpg pem file
* Update a couple URLs in secretary workbench sidebar

Small updates

---

www/members/meeting.cgi

As GitHub doesn't allow me to re-open #86 here the follow-up PR.
This PR;
- Ensures `MeetingUtil.calculate_quorum` is only called once.
- Updates the error message why the attendance record could not be calculated.
/cc @sebbASF

Improved members/meeting page

---

www/secretary/workbench/templates/emeritus-request.erb
www/secretary/workbench/views/actions/emeritus-request.json.rb
www/secretary/workbench/views/forms/emeritus-request.js.rb

I haven't actually run the tasks, but the output looks correct in the dry run.

Add tasks for emeritus request initial filing

---

www/roster/views/petri.html.rb

Reference the info.yaml file on the petri website

Petri info.yaml has moved

---

www/secretary/workbench/templates/incomplete.erb
www/secretary/workbench/views/parts.js.rb

Document reject 2 1

---

MACOSX.md

Update `MACOSX.md` to link to `DEVELOPMENT.md`

---

Rakefile

corrected path to config

---

www/secretary/workbench/views/actions/incomplete.json.rb
www/secretary/workbench/views/parts.js.rb

Remove unsigned form from special action
Add description to email text for unsigned and script font

Add script font to message

---

www/officers/surveys.cgi

Planning to start using the survey tool, so enabling the commit for testing

Enable checkin to start using surveys

---

lib/whimsy/asf/board.rb

See https://the-asf.slack.com/archives/C9NQ8G80Z/p1741424386833169?thread_ts=1741401945.288919&cid=C9NQ8G80Z.
Not sure if this is the way to fix. cc @sebbASF @ShaneCurcuru

chore: fix member info
